/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ApplicantId]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[Gender]
      ,[StreetAddress]
      ,[City]
      ,[State]
      ,[ZipCode]
      ,[Telephone]
      ,[Email]
      ,[DateOfBirth]
      ,[ApplicationReceivedDate]
      ,[EntryTerm]
      ,[ApplicationType]
      ,[Gpa]
      ,[SatMathScore]
      ,[SatReadingScore]
      ,[SatWritingScore]
      ,[EssayScore]
      ,[ApplicationStatus]
      ,[AdmissionPoints]
  FROM [Students].[dbo].[Applicants]